import type { NextPageWithLayout } from "./_app";
import Head from "next/head";
import type { ReactElement } from "react";

import Layout from "../components/Layout";
import FadeIn from "../components/FadeIn";

const Home: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <FadeIn>
        <h1 className="text-4xl text-purple-200 my-4">Hi</h1>
      </FadeIn>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      {page}
    </Layout>
  )
}

export default Home;
